language: groovy

install: true
cache:
    directories:
        - $HOME/.gradle

script:
    - mv -v settings.gradle{.travis,}
    - ./gradlew build

after_success:
    - ./gradlew jacocoTestReport coveralls